#!/usr/bin/env python

VERSION = '0.0.1'
APPNAME = 'ocaml_echo'

top = '.'
out = 'build'

def set_options(opts):
    pass

def configure(conf):
    conf.check_tool('ocaml')

def build(bld):
    obj = bld(features = 'ocaml',
            kind = 'all',
            includes = '.',
            target = APPNAME)
    obj.find_sources_in_dirs('.')

